---
galaxy_info:
  author: Accelize
  description: 'Install an application as Container service.'
  min_ansible_version: 2.8
  license: Apache License 2.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic

dependencies:
  - role: geerlingguy.docker
    when: not rootless|bool
    vars:
      docker_install_compose: false
