---
sudo: required
language: python
services: docker
dist: xenial

python:
    - "3.6"
    - "3.7"

install:
    # Python environment
    - "python -m pip install -U --upgrade-strategy eager setuptools pip wheel
       pytest-cov pytest-xdist codecov molecule[docker] --pre"

    # Installs all package dependencies
    - "python -m pip install -e ."

script:
    # Runs tests
    - 'pytest -vs -m "not require_csp" --cov=accelpy --cov-report=term-missing
      -n auto --dist=loadscope'

after_success:
    # Sends coverage to codecov.io
    - "codecov"
