---
# AWS CodeBuild
version: 0.2

env:
  parameter-store:
    XLZCRYPT_KEY: "xlzcrypt_key"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - $CODEBUILD_SRC_DIR_toolbox/install.py
      - xlz install accelpy_codebuild
      - export ACCELPY_NO_COLOR=True
      - python3 -m pip install -Uq setuptools pip wheel pytest-cov codecov
      - python3 -m pip install -qe .

  build:
    commands:
      - pytest -m require_csp --cov=accelpy --cov-report=term-missing

  post_build:
    commands:
      - codecov
