---
dependencies:
  - role: geerlingguy.docker
    vars:
      docker_install_compose: false
  - role: geerlingguy.kubernetes
    vars:
      kubernetes_role: "{{ master_node | ternary('master', 'node') }}"
      kubernetes_allow_pods_on_master: "{{ single_node }}"
