---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu_bionic
    image: ubuntu:bionic
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/lib/systemd/systemd"
    environment:
      container: docker

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      docker:
        rootless: false
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    # TODO: Remove once geerlingguy.kubernetes Failure on Docker fixed
    # - create
    # - prepare
    # - converge
    # - idempotence
    # - side_effect
    # - verify
    - cleanup
    - destroy
