---
- name: Ensure Apt cache is up to date
  apt:
    update_cache: true
  retries: 10
  delay: 1
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Ensure system is up to date
  apt:
    name: "*"
    state: latest  # noqa 403
    update_cache: true
    autoremove: true
    purge: true
  retries: 10
  delay: 1
  when: ansible_os_family == 'Debian'

- name: Ensure system is up to date
  yum:
    name: "*"
    state: latest  # noqa 403
  retries: 10
  delay: 1
  when: ansible_os_family == 'RedHat'

- name: Ensure FPGA user group exists
  group:
    name: fpgauser
    state: present

- name: Ensure application user exists and is in FPGA user group
  user:
    name: appuser
    shell: /bin/bash
    groups: fpgauser
    append: true
    create_home: true

- name: Accelize DRM, Move credential appuser home if service is disabled
  set_fact: accelize_drm_cred_dst="/home/appuser/.accelize_drm/cred.json"
  when: accelize_drm_disabled | bool

- name: Driver, force provider required driver over application driver
  set_fact: fpga_driver="{{ provider_required_driver }}"
  when: provider_required_driver is defined

- name: Driver, pass XRT version only if specified (Else use role default)
  set_fact: xilinx_xrt_version="{{ fpga_driver_version }}"
  when: fpga_driver_version is defined
