---
- name: Ensure Apt cache is up to date
  apt:
    update_cache: true
  retries: 10
  delay: 1
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Ensure system is up to date
  apt:
    name: "*"
    state: latest
    update_cache: true
    autoremove: true
    purge: true
  retries: 10
  delay: 1
  when: ansible_os_family == 'Debian'

- name: Ensure system is up to date
  yum:
    name: "*"
    state: latest
  retries: 10
  delay: 1
  when: ansible_os_family == 'RedHat'

- name: Ensure FPGA user group exists
  group:
    name: fpgauser
    state: present

- name: Ensure application user exists and is in FPGA user group
  user:
    name: appuser
    shell: /bin/bash
    groups: fpgauser
    append: true
    create_home: true
