---
dependencies:
  # System update
  - role: common.update_system

  # Security hardening
  - role: dev-sec.os-hardening
    vars:
      ufw_manage_defaults: false
      os_auth_pam_passwdqc_enable: false
    when: os_hardening | bool

  - role: dev-sec.ssh-hardening
    vars:
      ssh_allow_users: "{{ remote_user }}"
    when: ssh_hardening | bool

  # System reboot
  - role: common.reboot_system

  # FPGA drivers

  - role: 'accelize.aws_fpga'
    # TODO: Disabled, crash in AWS Udev script
    # vars:
    #   aws_fpga_allow_non_root: true
    #  aws_fpga_sdk_override_group: true
    when: fpga_driver == 'aws_f1'

  - role: 'accelize.xilinx_xrt'
    when: fpga_driver == 'xilinx_xrt'


  # Accelize DRM
  - accelize.accelize_drm
