---
dependencies:
  # System initialization
  - role: common.init_system

  # Security hardening
  - role: dev-sec.os-hardening
    vars:
      ufw_manage_defaults: false
      os_auth_pam_passwdqc_enable: false
    when: os_hardening | bool

  - role: dev-sec.ssh-hardening
    vars:
      ssh_allow_users: "{{ ansible_user }}"
    when: ssh_hardening | bool

  # System reboot
  - role: common.reboot_system

  # FPGA drivers
  - role: 'accelize.aws_fpga'
    vars:
      xilinx_xrt_version: "{{ fpga_driver_version }}"
      # TODO: Disabled, crash in AWS Udev script on CentOS
      # aws_fpga_allow_non_root: true
      # aws_fpga_sdk_override_group: true
    when: fpga_driver == 'aws_f1'

  - role: 'accelize.xilinx_xrt'
    vars:
      xilinx_xrt_version: "{{ fpga_driver_version }}"
    when: fpga_driver == 'xilinx_xrt'

  # Accelize DRM
  - role: accelize.accelize_drm
    vars:
      accelize_drm_driver_name: "{{ fpga_driver }}"
