---
galaxy_info:
  author: Accelize
  description: 'Initialize host with FPGA driver and common tasks.'
  min_ansible_version: 2.8
  license: Apache License 2.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic

dependencies:
  # Security hardening
  - role: dev-sec.os-hardening
    vars:
      ufw_manage_defaults: false
      os_auth_pam_passwdqc_enable: false

  # FPGA drivers
  - role: 'accelize.aws_fpga'
    vars:
      aws_fpga_allow_non_root: true
      aws_fpga_sdk_override_group: true
    when: accelize_drm_driver_name == 'aws_f1'

  # Accelize DRM
  - accelize.accelize_drm
