---
dependencies:
  # System update
  - role: common.update_system

  # Security hardening
  - role: dev-sec.os-hardening
    vars:
      ufw_manage_defaults: false
      os_auth_pam_passwdqc_enable: false
    when: os_hardening | bool

  - role: dev-sec.ssh-hardening
    vars:
      ssh_allow_users: "{{ remote_user }}"
    when: ssh_hardening | bool

  # System reboot
  - role: common.reboot_system

  # FPGA drivers

  - role: 'accelize.aws_fpga'
    vars:
      aws_fpga_allow_non_root: true
      aws_fpga_sdk_override_group: true
    when: accelize_drm_driver_name == 'aws_f1'

  - role: 'accelize.xilinx_xrt'
    when: accelize_drm_driver_name == 'xrt'

  # Accelize DRM
  - accelize.accelize_drm
