---
- name: Converge
  hosts: all
  roles:
    - role: container_service
  vars:
    app_packages:
      - name: accelize/accelpy-ci
        version: container_service
    accelize_drm_disabled: false
    accelize_drm_cred_dst: /home/appuser/.accelize_drm/cred.json
    firewall_rules:
      - start_port: 8080
        end_port: 8080
        protocol: tcp
        direction: ingress
    fpga_slots: [0]
