---
- name: Converge
  hosts: all
  roles:
    - role: container_service
  vars:
    package_name: accelize/accelpy-ci
    package_version: container_service
    firewall_rules:
      - start_port: 8080
        end_port: 8080
        protocol: tcp
        direction: ingress
    fpga_slots: [0]
