# Playbook template
- hosts: all
  become: true
  pre_tasks:

    # Set some variables if defined
    - set_fact: xilinx_xrt_version="{{ fpga_driver_version }}"
      when: fpga_driver_version is defined
